# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10R7DXiYRrp7tW3H3eUJY1HuxpzSLE-1Q
"""

# !pip install kaggle

# !mkdir -p ~/.kaggle
# !cp kaggle.json ~/.kaggle
# !chmod 600 ~/.kaggle/kaggle.json

# !kaggle datasets download -d zalando-research/fashionmnist

# !unzip fashionmnist.zip

# !pwd

# !mkdir Database_week5

# !cd Database_week5

# !touch my_python.py
# !ls


def state(b):
  x = 5*b+4
  print(x)

state(4)